import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localfont from 'next/font/local';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
const Spoqa = localfont({
  src: '../public/font/SpoqaHanSansNeo-Regular.ttf',
  weight: '400',
  variable: '--font-spoqa',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className={`${Spoqa.variable}`}>{children}</body>
    </html>
  );
}
